services:
  backend:
    build:
      context: ./backend
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    # depends_on:
    #   - db
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: always

  # db:
  #   image: postgres:latest
  #   env_file:
  #     - .env
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   restart: always
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

# volumes:
#   db_data: